routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::redirect('/', 'blog');

//web
Route::get('blog', 'Web\PageController@blog')->name('blog');
Route::get('entrada/{slug}', 'Web\PageController@post')->name('post');
Route::get('categoria/{slug}', 'Web\PageController@category')->name('category');
Route::get('etiqueta/{slug}', 'Web\PageController@tags')->name('tags');


//admin
Route::resource('tags', 'Admin\TagController');
Route::resource('categories', 'Admin\CategoryController');
Route::resource('posts', 'Admin\PostController');



/* Route::get('/home', 'HomeController@index')->name('home'); */

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'user_id', 'category_id', 'name', 'slug', 'excerpt', 'status', 'body', 'file'
    ];


    //relations

    public function user(){
        return $this->belongsTo(User::class);
    }

    public function category(){
        return $this->belongsTo(Category::class);
    }

    public function tags(){
        return $this->belongsToMany(Tag::class);
    }
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\PostStoreRequest;
use App\Http\Requests\PostUpdateRequest;
use App\Post;
use App\Tag;
use App\Category;
use Illuminate\Support\Facades\Storage;

class PostController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $posts = Post::orderBy('id', 'DESC')
                ->where('user_id', auth()->user()->id)
                ->paginate(5);

        return view('admin.post.index', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::orderBy('name', 'ASC')->pluck('name', 'id');

        $tags = Tag::orderBy('name', 'ASC')->get();

        return view('admin.post.create', compact('categories', 'tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostStoreRequest $request)
    {
        $post = Post::create($request->all());

        //imagen
        if($request->file('file')){
            $path = Storage::disk('public')->put('image', $request->file('file'));
            $post->fill(['file' => asset($path)])->save();
        }

        //tags
        $post->tags()->sync($request->get('tags'));


        return redirect()->route('posts.edit', $post->id)->with('info', 'Entrada creada con éxito');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::findOrFail($id);

        return view('admin.post.show', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $categories = Category::orderBy('name', 'ASC')->pluck('name', 'id');

        $tags = Tag::orderBy('name', 'ASC')->get();

        $post = Post::findOrFail($id);

        return view('admin.post.edit', compact('post', 'categories', 'tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostUpdateRequest $request, $id)
    {
        $post = Post::find($id);
        $post->fill($request->all())->save();

        if($request->file('file')){
            $path = Storage::disk('public')->put('image', $request->file('file'));
            $post->fill(['file' => asset($path)])->save();
        }

        //tags
        $post->tags()->sync($request->get('tags'));


        return redirect()->route('posts.edit', $post->id)->with('info', 'Entrada actualizada con éxito');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $post = Post::find($id)->delete();
        return back()->with('info', 'Eliminado correctamente');
    }
}

resources/views/admin/post/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

            <div class="row justify-content-md-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                          Crear Entrada
                        </div>

                        <div class="card-body">
                            {!! Form::open(['route' => 'posts.store', 'files' => 'true']) !!}
                                @include('admin.post.partials.form')
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>

    </div>




@endsection

resources/views/admin/post/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

            <div class="row justify-content-md-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                          Editar Entrada
                        </div>

                        <div class="card-body">
                            {!! Form::model($post, ['route' => ['posts.update', $post->id], 'method' => 'PUT', 'files' => 'true']) !!}
                                @include('admin.post.partials.form')
                            {!! Form::close() !!}
                        </div>
                    </div>
                </div>
            </div>

    </div>




@endsection

resources/views/admin/post/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

            <div class="row justify-content-md-center">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header">
                          Entradas
                          <a href="{{ route('posts.create') }}" class="btn btn-sm btn-primary pull-right">Crear</a>
                        </div>

                        <div class="card-body">
                            <table class="table table-striped table-hover">
                                <thead>
                                    <tr>

                                        <th width="30px">ID</th>
                                        <th width="60%">Nombre</th>
                                        <th colspan="3"></th>

                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach($posts as $post)
                                        <tr>
                                            <td width="30px">{{ $post->id }}</td>
                                            <td>{{ $post->name }}</td>

                                            <td>
                                                <a href="{{ route('posts.show', $post->id) }}" class="btn btn-outline-secondary btn-sm">Ver</a>
                                                <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-outline-secondary btn-sm">Editar</a>
                                                    <td>{!! Form::open(['route' => ['posts.destroy', $post->id], 'method' => 'DELETE']) !!}
                                                    <button class="btn btn-outline-danger btn-sm">Eliminar</button>
                                                    {!! Form::close() !!}
                                                    </td>
                                            </td>

                                        </tr>
                                    @endforeach

                                </tbody>

                            </table>
                        </div>
                    </div>

                    {{ $posts->render() }}

                </div>
            </div>

    </div>




@endsection

resources/views/admin/post/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container">

    <div class="col-md-12 col-md-offset-2">
        <h2>{{ $post->name }}</h2>



        <div class="card">

            <div class="card-header">
                Categoría
                <a href="{{ route('category', $post->category->slug) }}">{{ $post->category->name }}</a>
            </div>

            <div class="card-body">

                @if($post->file)
                <div class="box-img">
                    <img src="{{ $post->file }}" alt="">
                </div>
                @endif

                {{ $post->excerpt }}

                <hr>

                {!! $post->body !!}

                <hr>

                Etiquetas
                @foreach ($post->tags as $tag)
                    <a href="{{ route('blog', $tag->slug) }}">{{ $tag->name }}</a>
                @endforeach

            </div>

        </div>




    </div>

</div>


@endsection